
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: May 19 2026 17:50:36 IST (May 19 2026 12:20:36 UTC)

// Verification Directory fv/ddr_controller_top 

module ddr_controller_top(clk, rst_n, user_req_valid, user_req_rnw,
     user_req_bank, user_req_ready, ddr_cs_n, ddr_ras_n, ddr_cas_n,
     ddr_we_n);
  input clk, rst_n, user_req_valid, user_req_rnw;
  input [2:0] user_req_bank;
  output user_req_ready, ddr_cs_n, ddr_ras_n, ddr_cas_n, ddr_we_n;
  wire clk, rst_n, user_req_valid, user_req_rnw;
  wire [2:0] user_req_bank;
  wire user_req_ready, ddr_cs_n, ddr_ras_n, ddr_cas_n, ddr_we_n;
  wire [3:0] cmd_queue_count;
  wire [3:0] \cmd_queue_mem[4] ;
  wire [3:0] \cmd_queue_mem[0] ;
  wire [3:0] \cmd_queue_mem[2] ;
  wire [3:0] \cmd_queue_mem[6] ;
  wire [3:0] \cmd_queue_mem[7] ;
  wire [3:0] \cmd_queue_mem[3] ;
  wire [3:0] \cmd_queue_mem[5] ;
  wire [3:0] \cmd_queue_mem[1] ;
  wire [3:0] fifo_dout;
  wire [2:0] core_fsm_state;
  wire [2:0] cmd_queue_wr_ptr;
  wire [1:0] core_fsm_delay_cnt;
  wire [2:0] cmd_queue_rd_ptr;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10,
       UNCONNECTED11, UNCONNECTED12, UNCONNECTED13, UNCONNECTED14;
  wire UNCONNECTED15, UNCONNECTED16, UNCONNECTED17, UNCONNECTED18,
       UNCONNECTED19, UNCONNECTED20, core_fsm_bank_active, n_0;
  wire n_1, n_2, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_19, n_20, n_21, n_22, n_24, n_26;
  wire n_27, n_28, n_29, n_30, n_31, n_32, n_33, n_34;
  wire n_35, n_36, n_37, n_38, n_39, n_40, n_42, n_43;
  wire n_45, n_46, n_47, n_48, n_49, n_50, n_51, n_52;
  wire n_53, n_54, n_55, n_56, n_57, n_59, n_60, n_61;
  wire n_62, n_63, n_64, n_65, n_66, n_68, n_69, n_70;
  wire n_71, n_72, n_73, n_74, n_75, n_76, n_77, n_78;
  wire n_79, n_80, n_81, n_82, n_83, n_84, n_85, n_87;
  wire n_88, n_89, n_90, n_91, n_98, n_99;
  assign ddr_cs_n = 1'b0;
  DFFARX1 \cmd_queue_count_reg[3] (.RSTB (rst_n), .CLK (clk), .D
       (n_91), .Q (cmd_queue_count[3]), .QN (UNCONNECTED));
  AO22X1 g2641__2398(.IN1 (n_89), .IN2 (cmd_queue_count[3]), .IN3
       (n_64), .IN4 (cmd_queue_count[2]), .Q (n_91));
  DFFARX1 \cmd_queue_count_reg[2] (.RSTB (rst_n), .CLK (clk), .D
       (n_90), .Q (cmd_queue_count[2]), .QN (n_29));
  DFFARX1 \cmd_queue_count_reg[1] (.RSTB (rst_n), .CLK (clk), .D
       (n_99), .Q (cmd_queue_count[1]), .QN (UNCONNECTED0));
  AO222X1 g2645__5107(.IN1 (n_85), .IN2 (n_30), .IN3 (n_88), .IN4
       (cmd_queue_count[2]), .IN5 (n_87), .IN6 (n_15), .Q (n_90));
  OR3X1 g2644__6260(.IN1 (n_88), .IN2 (n_87), .IN3 (n_83), .Q (n_89));
  SDFFX1 \cmd_queue_mem_reg[4][3] (.CLK (clk), .D (\cmd_queue_mem[4]
       [3]), .SI (user_req_rnw), .SE (n_81), .Q (\cmd_queue_mem[4]
       [3]), .QN (UNCONNECTED1));
  SDFFX1 \cmd_queue_mem_reg[0][3] (.CLK (clk), .D (\cmd_queue_mem[0]
       [3]), .SI (user_req_rnw), .SE (n_80), .Q (\cmd_queue_mem[0]
       [3]), .QN (UNCONNECTED2));
  SDFFX1 \cmd_queue_mem_reg[2][3] (.CLK (clk), .D (user_req_rnw), .SI
       (\cmd_queue_mem[2] [3]), .SE (n_69), .Q (\cmd_queue_mem[2] [3]),
       .QN (UNCONNECTED3));
  SDFFX1 \cmd_queue_mem_reg[6][3] (.CLK (clk), .D (\cmd_queue_mem[6]
       [3]), .SI (user_req_rnw), .SE (n_76), .Q (\cmd_queue_mem[6]
       [3]), .QN (UNCONNECTED4));
  SDFFX1 \cmd_queue_mem_reg[7][3] (.CLK (clk), .D (\cmd_queue_mem[7]
       [3]), .SI (user_req_rnw), .SE (n_74), .Q (\cmd_queue_mem[7]
       [3]), .QN (UNCONNECTED5));
  SDFFX1 \cmd_queue_mem_reg[3][3] (.CLK (clk), .D (\cmd_queue_mem[3]
       [3]), .SI (user_req_rnw), .SE (n_78), .Q (\cmd_queue_mem[3]
       [3]), .QN (UNCONNECTED6));
  SDFFX1 \cmd_queue_mem_reg[5][3] (.CLK (clk), .D (\cmd_queue_mem[5]
       [3]), .SI (user_req_rnw), .SE (n_72), .Q (\cmd_queue_mem[5]
       [3]), .QN (UNCONNECTED7));
  SDFFX1 \cmd_queue_mem_reg[1][3] (.CLK (clk), .D (user_req_rnw), .SI
       (\cmd_queue_mem[1] [3]), .SE (n_71), .Q (\cmd_queue_mem[1] [3]),
       .QN (UNCONNECTED8));
  DFFARX1 \cmd_queue_dout_reg[3] (.RSTB (rst_n), .CLK (clk), .D (n_82),
       .Q (fifo_dout[3]), .QN (UNCONNECTED9));
  SDFFARX1 \cmd_queue_count_reg[0] (.RSTB (rst_n), .CLK (clk), .D
       (n_0), .SI (cmd_queue_count[0]), .SE (n_84), .Q
       (cmd_queue_count[0]), .QN (UNCONNECTED10));
  DFFARX1 \core_fsm_state_reg[0] (.RSTB (rst_n), .CLK (clk), .D (n_79),
       .Q (core_fsm_state[0]), .QN (n_4));
  AND2X1 g2659__8428(.IN1 (n_85), .IN2 (n_28), .Q (n_83));
  AO21X1 g2658__5526(.IN1 (n_63), .IN2 (n_13), .IN3 (n_84), .Q (n_88));
  NAND4X0 g2664__6783(.IN1 (n_53), .IN2 (n_54), .IN3 (n_59), .IN4
       (n_50), .QN (n_82));
  SDFFARX1 \core_fsm_state_reg[1] (.RSTB (rst_n), .CLK (clk), .D
       (n_56), .SI (n_55), .SE (core_fsm_state[1]), .Q
       (core_fsm_state[1]), .QN (UNCONNECTED11));
  NOR3X0 g2673__3680(.IN1 (n_75), .IN2 (cmd_queue_wr_ptr[0]), .IN3
       (cmd_queue_wr_ptr[1]), .QN (n_81));
  NOR3X0 g2672__1617(.IN1 (n_77), .IN2 (cmd_queue_wr_ptr[0]), .IN3
       (cmd_queue_wr_ptr[1]), .QN (n_80));
  NAND2X1 g2671__2802(.IN1 (n_61), .IN2 (n_31), .QN (n_79));
  NOR2X0 g2677__1705(.IN1 (n_77), .IN2 (n_73), .QN (n_78));
  NOR2X0 g2678__5122(.IN1 (n_75), .IN2 (n_68), .QN (n_76));
  NOR2X0 g2679__8246(.IN1 (n_75), .IN2 (n_73), .QN (n_74));
  NOR2X0 g2681__7098(.IN1 (n_75), .IN2 (n_70), .QN (n_72));
  OR2X1 g2682__6131(.IN1 (n_77), .IN2 (n_70), .Q (n_71));
  OR2X1 g2683__1881(.IN1 (n_77), .IN2 (n_68), .Q (n_69));
  SDFFARX1 \cmd_queue_wr_ptr_reg[0] (.RSTB (rst_n), .CLK (clk), .D
       (n_60), .SI (n_65), .SE (cmd_queue_wr_ptr[0]), .Q
       (cmd_queue_wr_ptr[0]), .QN (UNCONNECTED12));
  HADDX1 g2666__7482(.A0 (n_62), .B0 (n_65), .SO (n_84), .C1 (n_85));
  AND2X1 g2663__4733(.IN1 (n_63), .IN2 (n_14), .Q (n_64));
  AND2X1 g2660__6161(.IN1 (n_63), .IN2 (n_29), .Q (n_87));
  DFFARX1 \core_fsm_delay_cnt_reg[0] (.RSTB (rst_n), .CLK (clk), .D
       (n_57), .Q (core_fsm_delay_cnt[0]), .QN (UNCONNECTED13));
  SDFFARX1 \cmd_queue_rd_ptr_reg[2] (.RSTB (rst_n), .CLK (clk), .D
       (cmd_queue_rd_ptr[2]), .SI (n_27), .SE (n_62), .Q
       (cmd_queue_rd_ptr[2]), .QN (UNCONNECTED14));
  DFFARX1 \core_fsm_delay_cnt_reg[1] (.RSTB (rst_n), .CLK (clk), .D
       (n_52), .Q (core_fsm_delay_cnt[1]), .QN (UNCONNECTED15));
  SDFFARX1 \cmd_queue_rd_ptr_reg[1] (.RSTB (rst_n), .CLK (clk), .D
       (cmd_queue_rd_ptr[1]), .SI (n_17), .SE (n_62), .Q
       (cmd_queue_rd_ptr[1]), .QN (UNCONNECTED16));
  SDFFARX1 \cmd_queue_rd_ptr_reg[0] (.RSTB (rst_n), .CLK (clk), .D
       (n_62), .SI (n_49), .SE (cmd_queue_rd_ptr[0]), .Q
       (cmd_queue_rd_ptr[0]), .QN (UNCONNECTED17));
  SDFFARX1 \cmd_queue_wr_ptr_reg[2] (.RSTB (rst_n), .CLK (clk), .D
       (n_20), .SI (cmd_queue_wr_ptr[2]), .SE (n_65), .Q
       (cmd_queue_wr_ptr[2]), .QN (UNCONNECTED18));
  SDFFARX1 \cmd_queue_wr_ptr_reg[1] (.RSTB (rst_n), .CLK (clk), .D
       (n_18), .SI (cmd_queue_wr_ptr[1]), .SE (n_65), .Q
       (cmd_queue_wr_ptr[1]), .QN (UNCONNECTED19));
  NAND2X1 g2676__9315(.IN1 (n_48), .IN2 (n_32), .QN (n_61));
  NAND3X0 g2688__9945(.IN1 (n_60), .IN2 (rst_n), .IN3 (n_19), .QN
       (n_77));
  NAND4X0 g2691__2883(.IN1 (n_62), .IN2 (n_12), .IN3 (n_6), .IN4 (n_7),
       .QN (n_59));
  NAND3X0 g2693__2346(.IN1 (n_60), .IN2 (rst_n), .IN3
       (cmd_queue_wr_ptr[2]), .QN (n_75));
  NAND2X1 g2703__1666(.IN1 (n_46), .IN2 (n_51), .QN (n_57));
  NAND2X1 g2680__7410(.IN1 (n_43), .IN2 (n_55), .QN (n_56));
  NOR2X0 g2687__6417(.IN1 (n_65), .IN2 (n_62), .QN (n_63));
  NAND3X0 g2689__5477(.IN1 (n_62), .IN2 (n_38), .IN3
       (cmd_queue_rd_ptr[2]), .QN (n_54));
  NAND3X0 g2690__2398(.IN1 (n_62), .IN2 (n_37), .IN3 (n_26), .QN
       (n_53));
  AND2X1 g2694__5107(.IN1 (n_47), .IN2 (n_51), .Q (n_52));
  NAND2X0 g2684__6260(.IN1 (fifo_dout[3]), .IN2 (n_49), .QN (n_50));
  MUX21X1 g2692__4319(.IN1 (n_42), .IN2 (n_10), .S (core_fsm_state[1]),
       .Q (n_48));
  INVX0 g2696(.INP (n_65), .ZN (n_60));
  MUX21X1 g2704__8428(.IN1 (n_11), .IN2 (core_fsm_delay_cnt[1]), .S
       (n_45), .Q (n_47));
  XOR2X1 g2708__5526(.IN1 (n_45), .IN2 (core_fsm_delay_cnt[0]), .Q
       (n_46));
  NAND2X1 g2698__6783(.IN1 (user_req_valid), .IN2 (user_req_ready), .QN
       (n_65));
  NAND3X0 g2685__3680(.IN1 (n_42), .IN2 (core_fsm_bank_active), .IN3
       (core_fsm_state[2]), .QN (n_43));
  DFFARX1 core_fsm_bank_active_reg(.RSTB (rst_n), .CLK (clk), .D
       (n_40), .Q (core_fsm_bank_active), .QN (UNCONNECTED20));
  DFFARX1 \core_fsm_state_reg[2] (.RSTB (rst_n), .CLK (clk), .D (n_33),
       .Q (n_3), .QN (core_fsm_state[2]));
  INVX0 g2697(.INP (n_49), .ZN (n_62));
  OR2X1 g2699__1617(.IN1 (n_39), .IN2 (ddr_cas_n), .Q (n_49));
  NAND2X1 g2707__2802(.IN1 (n_51), .IN2 (n_21), .QN (n_40));
  NAND2X1 g2705__1705(.IN1 (n_22), .IN2 (cmd_queue_count[3]), .QN
       (user_req_ready));
  INVX0 g2700(.INP (n_39), .ZN (n_42));
  AO222X1 g2711__5122(.IN1 (n_34), .IN2 (\cmd_queue_mem[7] [3]), .IN3
       (n_36), .IN4 (\cmd_queue_mem[5] [3]), .IN5 (n_35), .IN6
       (\cmd_queue_mem[6] [3]), .Q (n_38));
  AO222X1 g2712__8246(.IN1 (n_36), .IN2 (\cmd_queue_mem[1] [3]), .IN3
       (n_35), .IN4 (\cmd_queue_mem[2] [3]), .IN5 (n_34), .IN6
       (\cmd_queue_mem[3] [3]), .Q (n_37));
  OAI21X1 g2715__7098(.IN1 (n_24), .IN2 (n_32), .IN3 (n_31), .QN
       (n_33));
  OAI21X1 g2714__6131(.IN1 (n_29), .IN2 (n_16), .IN3 (n_28), .QN
       (n_30));
  MUX21X1 g2718__1881(.IN1 (cmd_queue_rd_ptr[2]), .IN2 (n_26), .S
       (n_34), .Q (n_27));
  NOR2X0 g2702__5115(.IN1 (n_28), .IN2 (cmd_queue_count[3]), .QN
       (n_39));
  NAND3X0 g2716__7482(.IN1 (n_31), .IN2 (n_9), .IN3 (n_24), .QN
       (ddr_ras_n));
  AO222X1 g2710__4733(.IN1 (core_fsm_state[0]), .IN2 (n_24), .IN3
       (n_5), .IN4 (core_fsm_state[2]), .IN5 (n_3), .IN6
       (core_fsm_state[1]), .Q (ddr_we_n));
  NAND2X1 g2722__6161(.IN1 (n_32), .IN2 (core_fsm_state[1]), .QN
       (n_45));
  INVX0 g2706(.INP (n_28), .ZN (n_22));
  NAND2X1 g2713__9315(.IN1 (n_8), .IN2 (core_fsm_bank_active), .QN
       (n_21));
  MUX21X1 g2717__9945(.IN1 (n_19), .IN2 (cmd_queue_wr_ptr[2]), .S
       (n_73), .Q (n_20));
  NAND2X1 g2724__2883(.IN1 (n_68), .IN2 (n_70), .QN (n_18));
  OR2X1 g2725__2346(.IN1 (n_36), .IN2 (n_35), .Q (n_17));
  OR2X1 g2720__1666(.IN1 (n_16), .IN2 (n_15), .Q (n_66));
  NOR2X0 g2719__7410(.IN1 (n_13), .IN2 (cmd_queue_count[3]), .QN
       (n_14));
  OR2X1 g2721__6417(.IN1 (n_55), .IN2 (core_fsm_state[1]), .Q (n_51));
  NAND2X1 g2723__5477(.IN1 (n_16), .IN2 (n_29), .QN (n_28));
  MUX21X1 g2728__2398(.IN1 (\cmd_queue_mem[4] [3]), .IN2
       (\cmd_queue_mem[0] [3]), .S (n_26), .Q (n_12));
  AO21X1 g2726__5107(.IN1 (core_fsm_delay_cnt[0]), .IN2
       (core_fsm_delay_cnt[1]), .IN3 (n_10), .Q (n_11));
  OR2X1 g2729__6260(.IN1 (n_55), .IN2 (n_24), .Q (ddr_cas_n));
  INVX0 g2736(.INP (n_9), .ZN (n_32));
  OR3X1 g2727__4319(.IN1 (core_fsm_state[1]), .IN2 (core_fsm_state[2]),
       .IN3 (core_fsm_state[0]), .Q (n_8));
  NAND2X1 g2731__8428(.IN1 (cmd_queue_wr_ptr[1]), .IN2 (n_1), .QN
       (n_68));
  NOR2X0 g2732__5526(.IN1 (cmd_queue_rd_ptr[0]), .IN2 (n_7), .QN
       (n_35));
  NOR2X0 g2733__6783(.IN1 (cmd_queue_rd_ptr[1]), .IN2 (n_6), .QN
       (n_36));
  NAND2X1 g2734__3680(.IN1 (cmd_queue_wr_ptr[0]), .IN2 (n_2), .QN
       (n_70));
  OR2X1 g2730__1617(.IN1 (fifo_dout[3]), .IN2 (n_4), .Q (n_5));
  NAND2X1 g2741__2802(.IN1 (core_fsm_state[2]), .IN2 (n_4), .QN (n_9));
  INVX0 g2737(.INP (n_13), .ZN (n_15));
  NOR2X0 g2742__1705(.IN1 (n_7), .IN2 (n_6), .QN (n_34));
  NAND2X1 g2739__5122(.IN1 (n_3), .IN2 (core_fsm_state[0]), .QN (n_31));
  NAND2X1 g2743__8246(.IN1 (cmd_queue_wr_ptr[1]), .IN2
       (cmd_queue_wr_ptr[0]), .QN (n_73));
  NAND2X1 g2744__7098(.IN1 (cmd_queue_count[1]), .IN2
       (cmd_queue_count[0]), .QN (n_13));
  NOR2X0 g2738__6131(.IN1 (core_fsm_delay_cnt[0]), .IN2
       (core_fsm_delay_cnt[1]), .QN (n_10));
  NOR2X0 g2740__1881(.IN1 (cmd_queue_count[0]), .IN2
       (cmd_queue_count[1]), .QN (n_16));
  NAND2X1 g2735__5115(.IN1 (core_fsm_state[0]), .IN2
       (core_fsm_state[2]), .QN (n_55));
  INVX0 g2747(.INP (cmd_queue_wr_ptr[1]), .ZN (n_2));
  INVX0 g2753(.INP (cmd_queue_wr_ptr[2]), .ZN (n_19));
  INVX0 g2746(.INP (cmd_queue_rd_ptr[0]), .ZN (n_6));
  INVX0 g2750(.INP (cmd_queue_rd_ptr[2]), .ZN (n_26));
  INVX0 g2752(.INP (cmd_queue_rd_ptr[1]), .ZN (n_7));
  INVX0 g2754(.INP (cmd_queue_wr_ptr[0]), .ZN (n_1));
  INVX0 g2745(.INP (cmd_queue_count[0]), .ZN (n_0));
  INVX0 g2755(.INP (core_fsm_state[1]), .ZN (n_24));
  AO21X1 g2(.IN1 (n_84), .IN2 (cmd_queue_count[1]), .IN3 (n_98), .Q
       (n_99));
  MUX21X1 g3(.IN1 (n_63), .IN2 (n_85), .S (n_66), .Q (n_98));
endmodule

